_ConfigPhone = {
    defaultBackground = "",
    phoneItemName = "phone",

    applications = {
        ["phone"] = {
            app = "phone",
            color = "#04b543",
            icon = "fa fa-phone-alt",
            tooltipText = "Téléphone",
            tooltipPos = "top",
            job = false,
            blockedjobs = {},
            slot = 1,
            Alerts = 0,
        },
        ["whatsapp"] = {
            app = "whatsapp",
            color = "#25d366",
            icon = "fab fa-whatsapp",
            tooltipText = "Whatsapp",
            tooltipPos = "top",
            style = "font-size: 2.8vh";
            job = false,
            blockedjobs = {},
            slot = 2,
            Alerts = 0,
        },
        ["twitter"] = {
            app = "twitter",
            color = "#1da1f2",
            icon = "fab fa-twitter",
            tooltipText = "Twitter",
            tooltipPos = "top",
            job = false,
            blockedjobs = {},
            slot = 3,
            Alerts = 0,
        },
        ["settings"] = {
            app = "settings",
            color = "#636e72",
            icon = "fa fa-cog",
            tooltipText = "Paramètre",
            tooltipPos = "top",
            style = "padding-right: .08vh; font-size: 2.3vh";
            job = false,
            blockedjobs = {},
            slot = 4,
            Alerts = 0,
        },
        ["garage"] = {
            app = "garage",
            color = "#575fcf",
            icon = "fas fa-warehouse",
            tooltipText = "Garage",
            job = false,
            blockedjobs = {},
            slot = 5,
            Alerts = 0,
        },
        ["mail"] = {
            app = "mail",
            color = "#ff002f",
            icon = "fas fa-envelope",
            tooltipText = "Email",
            job = false,
            blockedjobs = {},
            slot = 6,
            Alerts = 0,
        },
        ["advert"] = {
            app = "advert",
            color = "#ff8f1a",
            icon = "fas fa-ad",
            tooltipText = "Sarı Sayfalar",
            job = false,
            blockedjobs = {},
            slot = 7,
            Alerts = 0,
        },
        ["bank"] = {
            app = "bank",
            color = "#9c88ff",
            icon = "fas fa-university",
            tooltipText = "Banque",
            job = false,
            blockedjobs = {},
            slot = 8,
            Alerts = 0,
        },
        ["racing"] = {
            app = "racing",
            color = "#353b48",
            icon = "fas fa-flag-checkered",
            tooltipText = "Yarış Uygulaması",
            job = false,
            blockedjobs = {},
            slot = 9,
            Alerts = 0,
        },
        ["lawyers"] = {
            app = "lawyers",
            color = "#0061e0",
            icon = "fas fa-building",
            tooltipText = "Aktif Polis",
            job = false,
            blockedjobs = {},
            slot = 10,
            Alerts = 0,
        },
        ["spotify"] = {
            app = "spotify",
            color = "#82c91e",
            icon = "fab fa-spotify",
            tooltipText = "Spotify",
            job = false,
            blockedjobs = {},
            slot = 11,
            Alerts = 0,
        },
        ["bbc"] = {
            app = "bbc",
            color = "#ff0000",
            icon = "fas fa-newspaper",
            tooltipText = "Haberler",
            job = false,
            blockedjobs = {},
            slot = 12,
            Alerts = 0,
        },
        ["snake"] = {
            app = "snake",
            color = "#609",
            icon = "fas fa-ghost",
            tooltipText = "Yılan Oyunu",
            job = false,
            blockedjobs = {},
            slot = 13,
            Alerts = 0,
        },
        ["solitary"] = {
            app = "solitary",
            color = "#e6bb12",
            icon = "fas fa-crown",
            tooltipText = "Kart Oyunu",
            job = false,
            blockedjobs = {},
            slot = 14,
            Alerts = 0,
        },
    },
}