--[[
  This file is part of FlashLand.
  Created at 08/12/2021 23:32
  
  Copyright (c) FlashLand - All Rights Reserved
  
  Unauthorized using, copying, modifying and/or distributing of this file,
  via any medium is strictly prohibited. This code is confidential.
--]]
---@author VibR1cY

_Static_Animation = {
    expression = {
        { label = "Enervé", name = "mood_angry_1" },
        { label = "Enervé 2", name = "effort_2" },
        { label = "Bourré", name = "mood_drunk_1" },
        { label = "Blessé", name = "pose_injured_1" },
        { label = "Electrocuté", name = "electrocuted_1" },
        { label = "Méfiant", name = "effort_1" },
        { label = "Méfiant 2", name = "mood_drivefast_1" },
        { label = "Méfiant 3", name = "pose_angry_1" },
        { label = "Méfiant 3", name = "pose_angry_1" },
        { label = "Content", name = "mood_happy_1" },
        { label = "Dépité", name = "mood_injured_1" },
        { label = "Déprimé", name = "mood_dancing_low_1" },
        { label = "Choqué", name = "smoking_hold_1" },
        { label = "Choqué 2", name = "shocked_1" },
        { label = "Choqué 3", name = "shocked_2" },
        { label = "Endormi", name = "mood_sleeping_1" },
        { label = "Assoupi", name = "dead_1" },
        { label = "Anxieux", name = "mood_aiming_1" },
        { label = "Stressée", name = "mood_stressed_1" },
        { label = "Capricieux", name = "mood_sulk_1" },
        { label = "Soupçonneux", name = "effort_3" },
    },
    process = {
        { label = "1", name = "move_m@alien" },
        { label = "2", name = "anim_group_move_ballistic" },
        { label = "3", name = "move_f@arrogant@a" },
        { label = "4", name = "move_m@brave" },
        { label = "5", name = "move_m@casual@a" },
        { label = "6", name = "move_m@casual@b" },
        { label = "7", name = "move_m@casual@c" },
        { label = "8", name = "move_m@casual@d" },
        { label = "9", name = "move_m@casual@e" },
        { label = "10", name = "move_m@casual@f" },
        { label = "11", name = "move_f@chichi" },
        { label = "12", name = "move_m@confident" },
        { label = "13", name = "move_m@business@a" },
        { label = "14", name = "move_m@business@b" },
        { label = "15", name = "move_m@business@c" },
        { label = "16", name = "move_f@multiplayer" },
        { label = "17", name = "move_m@multiplayer" },
        { label = "18", name = "move_m@drunk@a" },
        { label = "19", name = "move_m@drunk@slightlydrunk" },
        { label = "20", name = "move_m@buzzed" },
        { label = "21", name = "move_m@drunk@verydrunk" },
        { label = "22", name = "move_f@femme@" },
        { label = "23", name = "move_characters@franklin@fire" },
        { label = "24", name = "move_characters@michael@fire" },
        { label = "25", name = "move_m@fire" },
        { label = "26", name = "move_f@flee@a" },
        { label = "26", name = "move_p_m_one" },
        { label = "27", name = "move_m@gangster@generic" },
        { label = "28", name = "move_m@gangster@ng" },
        { label = "29", name = "move_m@gangster@var_e" },
        { label = "30", name = "move_m@gangster@var_f" },
        { label = "31", name = "move_m@gangster@var_i" },
        { label = "32", name = "anim@move_m@grooving@" },
        { label = "33", name = "move_m@prison_gaurd" },
        { label = "34", name = "move_m@prisoner_cuffed" },
        { label = "35", name = "move_f@heels@c" },
        { label = "36", name = "move_f@heels@d" },
        { label = "37", name = "move_m@hiking" },
        { label = "38", name = "move_m@hipster@a" },
        { label = "39", name = "move_m@hobo@a" },
        { label = "40", name = "move_f@hurry@a" },
        { label = "41", name = "move_p_m_zero_janitor" },
        { label = "42", name = "move_p_m_zero_slow" },
        { label = "43", name = "move_m@jog@" },
        { label = "44", name = "anim_group_move_lemar_alley" },
        { label = "45", name = "move_heist_lester" },
        { label = "46", name = "move_lester_caneup" },
        { label = "47", name = "move_f@maneater" },
        { label = "48", name = "move_ped_bucket" },
        { label = "49", name = "move_m@money" },
        { label = "50", name = "move_m@muscle@a" },
        { label = "51", name = "move_m@posh@" },
        { label = "52", name = "move_m@quick" },
        { label = "53", name = "female_fast_runner" },
        { label = "54", name = "move_m@sad@a" },
        { label = "55", name = "move_m@sassy" },
        { label = "56", name = "move_f@sassy" },
        { label = "57", name = "move_f@scared" },
        { label = "58", name = "move_f@sexy@a" },
        { label = "59", name = "move_m@shadyped@a" },
        { label = "60", name = "move_characters@jimmy@slow@" },
        { label = "61", name = "move_m@swagger" },
        { label = "62", name = "move_m@tough_guy@" },
        { label = "63", name = "move_f@tough_guy@" },
        { label = "64", name = "clipset@move@trash_fast_turn" },
        { label = "65", name = "missfbi4prepp1_garbageman" },
        { label = "66", name = "move_p_m_two" },
        { label = "67", name = "move_m@bag" },
    },
    animation = {
        { label = "", dict = "", name = "" },
    },
}